name: Executar proves Python mixtes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositori
      uses: actions/checkout@v3

    - name: Instal·lar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instal·lar pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Executar proves amb pytest
      run: |
        pytest JanPinto_pytest1.py

    - name: Executar proves unittest
      run: |
        python unitest.py
